/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '//(index)'
      | '//blank-page'
      | '//example/charts'
      | '//example/composables/use-axios'
      | '//example/composables/use-base'
      | '//example/composables/use-pagefecth'
      | '//example/content-text'
      | '//example/crud-table'
      | '//example/drag-drop'
      | '//example/emoji-picker'
      | '//example/image-cropper'
      | '//example/image-view'
      | '//example/infinite-scroll'
      | '//example/markdown-editor'
      | '//example/result'
      | '//example/swiper'
      | '//example/ui/avatar'
      | '//example/ui/button'
      | '//example/ui/card'
      | '//example/ui/date-picker'
      | '//example/ui/dialog'
      | '//example/ui/file-picker'
      | '//example/ui/input-text'
      | '//example/ui/menu'
      | '//example/ui/select'
      | '//example/ui/tabs'
      | '//example/ui/toggle'
      | '//example/ui/transitions'
      | '//example/ui/user'
      | '//example/virtual-scroller'
      | '//permission/'
      | '//permission/[crud]/[id]'
      | '//role/'
      | '//role/[crud]/[id]'
      | '//settings/'
      | '//settings/emails'
      | '//settings/notifications'
      | '//settings/security'
      | '//test-page-fetch'
      | '//user/'
      | '//user/[crud]/[id]'
    >,
    '//(index)': RouteRecordInfo<
      '//(index)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//blank-page': RouteRecordInfo<
      '//blank-page',
      '/blank-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/charts': RouteRecordInfo<
      '//example/charts',
      '/example/charts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/composables/use-axios': RouteRecordInfo<
      '//example/composables/use-axios',
      '/example/composables/use-axios',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/composables/use-base': RouteRecordInfo<
      '//example/composables/use-base',
      '/example/composables/use-base',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/composables/use-pagefecth': RouteRecordInfo<
      '//example/composables/use-pagefecth',
      '/example/composables/use-pagefecth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/content-text': RouteRecordInfo<
      '//example/content-text',
      '/example/content-text',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/crud-table': RouteRecordInfo<
      '//example/crud-table',
      '/example/crud-table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/drag-drop': RouteRecordInfo<
      '//example/drag-drop',
      '/example/drag-drop',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/emoji-picker': RouteRecordInfo<
      '//example/emoji-picker',
      '/example/emoji-picker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/image-cropper': RouteRecordInfo<
      '//example/image-cropper',
      '/example/image-cropper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/image-view': RouteRecordInfo<
      '//example/image-view',
      '/example/image-view',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/infinite-scroll': RouteRecordInfo<
      '//example/infinite-scroll',
      '/example/infinite-scroll',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/markdown-editor': RouteRecordInfo<
      '//example/markdown-editor',
      '/example/markdown-editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/result': RouteRecordInfo<
      '//example/result',
      '/example/result',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/swiper': RouteRecordInfo<
      '//example/swiper',
      '/example/swiper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/ui/avatar': RouteRecordInfo<
      '//example/ui/avatar',
      '/example/ui/avatar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/ui/button': RouteRecordInfo<
      '//example/ui/button',
      '/example/ui/button',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/ui/card': RouteRecordInfo<
      '//example/ui/card',
      '/example/ui/card',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/ui/date-picker': RouteRecordInfo<
      '//example/ui/date-picker',
      '/example/ui/date-picker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/ui/dialog': RouteRecordInfo<
      '//example/ui/dialog',
      '/example/ui/dialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/ui/file-picker': RouteRecordInfo<
      '//example/ui/file-picker',
      '/example/ui/file-picker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/ui/input-text': RouteRecordInfo<
      '//example/ui/input-text',
      '/example/ui/input-text',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/ui/menu': RouteRecordInfo<
      '//example/ui/menu',
      '/example/ui/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/ui/select': RouteRecordInfo<
      '//example/ui/select',
      '/example/ui/select',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/ui/tabs': RouteRecordInfo<
      '//example/ui/tabs',
      '/example/ui/tabs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/ui/toggle': RouteRecordInfo<
      '//example/ui/toggle',
      '/example/ui/toggle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/ui/transitions': RouteRecordInfo<
      '//example/ui/transitions',
      '/example/ui/transitions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/ui/user': RouteRecordInfo<
      '//example/ui/user',
      '/example/ui/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//example/virtual-scroller': RouteRecordInfo<
      '//example/virtual-scroller',
      '/example/virtual-scroller',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//permission/': RouteRecordInfo<
      '//permission/',
      '/permission',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//permission/[crud]/[id]': RouteRecordInfo<
      '//permission/[crud]/[id]',
      '/permission/:crud/:id',
      { crud: ParamValue<true>, id: ParamValue<true> },
      { crud: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '//role/': RouteRecordInfo<
      '//role/',
      '/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//role/[crud]/[id]': RouteRecordInfo<
      '//role/[crud]/[id]',
      '/role/:crud/:id',
      { crud: ParamValue<true>, id: ParamValue<true> },
      { crud: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '//settings/': RouteRecordInfo<
      '//settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//settings/emails': RouteRecordInfo<
      '//settings/emails',
      '/settings/emails',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//settings/notifications': RouteRecordInfo<
      '//settings/notifications',
      '/settings/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//settings/security': RouteRecordInfo<
      '//settings/security',
      '/settings/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//test-page-fetch': RouteRecordInfo<
      '//test-page-fetch',
      '/test-page-fetch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//user/': RouteRecordInfo<
      '//user/',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//user/[crud]/[id]': RouteRecordInfo<
      '//user/[crud]/[id]',
      '/user/:crud/:id',
      { crud: ParamValue<true>, id: ParamValue<true> },
      { crud: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '/[...catchAll]': RouteRecordInfo<
      '/[...catchAll]',
      '/:catchAll(.*)',
      { catchAll: ParamValue<true> },
      { catchAll: ParamValue<false> },
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/login'
      | '/auth/signup'
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/signup': RouteRecordInfo<
      '/auth/signup',
      '/auth/signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/chats': RouteRecordInfo<
      '/chats',
      '/chats',
      Record<never, never>,
      Record<never, never>,
      | '/chats/g/[id]'
    >,
    '/chats/g/[id]': RouteRecordInfo<
      '/chats/g/[id]',
      '/chats/g/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/error': RouteRecordInfo<
      '/error',
      '/error',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error500': RouteRecordInfo<
      '/error500',
      '/error500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feed': RouteRecordInfo<
      '/feed',
      '/feed',
      Record<never, never>,
      Record<never, never>,
      | '/feed/(index)'
    >,
    '/feed/(index)': RouteRecordInfo<
      '/feed/(index)',
      '/feed',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test': RouteRecordInfo<
      '/test',
      '/test',
      Record<never, never>,
      Record<never, never>,
      | '/test/(index)'
    >,
    '/test/(index)': RouteRecordInfo<
      '/test/(index)',
      '/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
        | '//(index)'
        | '//blank-page'
        | '//example/charts'
        | '//example/composables/use-axios'
        | '//example/composables/use-base'
        | '//example/composables/use-pagefecth'
        | '//example/content-text'
        | '//example/crud-table'
        | '//example/drag-drop'
        | '//example/emoji-picker'
        | '//example/image-cropper'
        | '//example/image-view'
        | '//example/infinite-scroll'
        | '//example/markdown-editor'
        | '//example/result'
        | '//example/swiper'
        | '//example/ui/avatar'
        | '//example/ui/button'
        | '//example/ui/card'
        | '//example/ui/date-picker'
        | '//example/ui/dialog'
        | '//example/ui/file-picker'
        | '//example/ui/input-text'
        | '//example/ui/menu'
        | '//example/ui/select'
        | '//example/ui/tabs'
        | '//example/ui/toggle'
        | '//example/ui/transitions'
        | '//example/ui/user'
        | '//example/virtual-scroller'
        | '//permission/'
        | '//permission/[crud]/[id]'
        | '//role/'
        | '//role/[crud]/[id]'
        | '//settings/'
        | '//settings/emails'
        | '//settings/notifications'
        | '//settings/security'
        | '//test-page-fetch'
        | '//user/'
        | '//user/[crud]/[id]'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/index/(index).vue': {
      routes:
        | '//(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/blank-page.vue': {
      routes:
        | '//blank-page'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/charts.vue': {
      routes:
        | '//example/charts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/composables/use-axios.vue': {
      routes:
        | '//example/composables/use-axios'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/composables/use-base.vue': {
      routes:
        | '//example/composables/use-base'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/composables/use-pagefecth.vue': {
      routes:
        | '//example/composables/use-pagefecth'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/content-text.vue': {
      routes:
        | '//example/content-text'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/crud-table.vue': {
      routes:
        | '//example/crud-table'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/drag-drop.vue': {
      routes:
        | '//example/drag-drop'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/emoji-picker.vue': {
      routes:
        | '//example/emoji-picker'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/image-cropper.vue': {
      routes:
        | '//example/image-cropper'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/image-view.vue': {
      routes:
        | '//example/image-view'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/infinite-scroll.vue': {
      routes:
        | '//example/infinite-scroll'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/markdown-editor.vue': {
      routes:
        | '//example/markdown-editor'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/result.vue': {
      routes:
        | '//example/result'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/swiper.vue': {
      routes:
        | '//example/swiper'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/ui/avatar.vue': {
      routes:
        | '//example/ui/avatar'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/ui/button.vue': {
      routes:
        | '//example/ui/button'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/ui/card.vue': {
      routes:
        | '//example/ui/card'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/ui/date-picker.vue': {
      routes:
        | '//example/ui/date-picker'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/ui/dialog.vue': {
      routes:
        | '//example/ui/dialog'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/ui/file-picker.vue': {
      routes:
        | '//example/ui/file-picker'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/ui/input-text.vue': {
      routes:
        | '//example/ui/input-text'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/ui/menu.vue': {
      routes:
        | '//example/ui/menu'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/ui/select.vue': {
      routes:
        | '//example/ui/select'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/ui/tabs.vue': {
      routes:
        | '//example/ui/tabs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/ui/toggle.vue': {
      routes:
        | '//example/ui/toggle'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/ui/transitions.vue': {
      routes:
        | '//example/ui/transitions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/ui/user.vue': {
      routes:
        | '//example/ui/user'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/example/virtual-scroller.vue': {
      routes:
        | '//example/virtual-scroller'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/permission/index.vue': {
      routes:
        | '//permission/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/permission/[crud]/[id].vue': {
      routes:
        | '//permission/[crud]/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/index/role/index.vue': {
      routes:
        | '//role/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/role/[crud]/[id].vue': {
      routes:
        | '//role/[crud]/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/index/settings/index.vue': {
      routes:
        | '//settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/settings/emails.vue': {
      routes:
        | '//settings/emails'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/settings/notifications.vue': {
      routes:
        | '//settings/notifications'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/settings/security.vue': {
      routes:
        | '//settings/security'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/test-page-fetch.vue': {
      routes:
        | '//test-page-fetch'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/user/index.vue': {
      routes:
        | '//user/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/user/[crud]/[id].vue': {
      routes:
        | '//user/[crud]/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/[...catchAll].vue': {
      routes:
        | '/[...catchAll]'
      views:
        | never
      pathParamNames:
        | 'catchAll'
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/login'
        | '/auth/signup'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/signup.vue': {
      routes:
        | '/auth/signup'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/chats.vue': {
      routes:
        | '/chats'
        | '/chats/g/[id]'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/chats/g/[id].vue': {
      routes:
        | '/chats/g/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/error.vue': {
      routes:
        | '/error'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/error500.vue': {
      routes:
        | '/error500'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/feed.vue': {
      routes:
        | '/feed'
        | '/feed/(index)'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/feed/(index).vue': {
      routes:
        | '/feed/(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/test.vue': {
      routes:
        | '/test'
        | '/test/(index)'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/test/(index).vue': {
      routes:
        | '/test/(index)'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
